name: StarRocks UT
trigger:
  change:
    types: [ submit, create, push ]

jobs:
  ut-fe:
    image: hub.byted.org/compile/emr-starrocks-lh-3.2-builder:e5e4770c45e7dde16c46769503a2ebc1
    working-directory: emr-core/StarRocks
    runs-on:
      spec: m1.8xlarge
    steps:
      - name: fe
        commands:
          - mkdir -p /root/.m2/
          - cp .codebase/settings.xml /root/.m2/
          - sh run-fe-ut.sh
  ut-be:
    image: hub.byted.org/compile/emr-starrocks-lh-3.2-builder:e5e4770c45e7dde16c46769503a2ebc1
    working-directory: emr-core/StarRocks
    runs-on:
      spec: m1.8xlarge
    steps:
      - name: be
        commands:
          # -j 12 to avoid kill by system while linking
          - sh run-be-ut.sh --use-staros -j 12


  starrocks_format_sdk:
    image:  hub.byted.org/compile/emr-starrocks-lh-3.2-builder:a34aa9858eee6be10bdebc5dfad3a04c
    working-directory: emr-core/StarRocks
    runs-on:
      spec: m1.8xlarge
    steps:
      - name: run-sr-format-sdk-test
        commands:
          - mkdir -p /root/.m2/
          - cp .codebase/settings.xml /root/.m2/
          - sh .codebase/run-sr-format-sdk-test.sh


